Repository reactiveui/splat, pull requests merged in 2019-02, with the labels that each got.

#250 WIP Read only ILogger Loglevel
  README.md
  src/Splat.Log4Net/Log4NetLogger.cs
  src/Splat.NLog/NLogLogger.cs
  src/Splat.Serilog/SerilogLogger.cs
  src/Splat.Tests/API/ApiApprovalTests.SplatProject.net472.approved.txt
  src/Splat.Tests/API/ApiApprovalTests.SplatProject.netcoreapp2.1.approved.txt
  src/Splat.Tests/Logging/FullLoggerExtensionsTests.cs
  src/Splat/Logging/ILogger.cs
  src/Splat/Logging/WrappingFullLogger.cs
  src/Splat/Logging/WrappingPrefixLogger.cs
Labels: Breaking change, developer-experience

#271 bug: locator documentation
  README.md
Labels: developer-experience

#278 addition of Microsoft.Extensions.Logging adapter
  README.md
  build.cake
  src/Splat.Microsoft.Extensions.Logging/MicrosoftExtensionsLoggingLogger.cs
  src/Splat.Microsoft.Extensions.Logging/MutableDependencyResolverExtensions.cs
  src/Splat.Microsoft.Extensions.Logging/Splat.Microsoft.Extensions.Logging.csproj
  src/Splat.Tests/Logging/MicrosoftExtensionsLoggingLoggerTests.cs
  src/Splat.Tests/Logging/MockActualMicrosoftExtensionsLoggingLogger.cs
  src/Splat.Tests/Splat.Tests.csproj
  src/Splat.sln
Labels: Feature

#279 feature: Added Splat.Ninject
  build.cake
  src/Directory.build.props
  src/Splat.Ninject.Tests/DependencyResolverTests.cs
  src/Splat.Ninject.Tests/Splat.Ninject.Tests.csproj
  src/Splat.Ninject/NinjectDependencyResolver.cs
  src/Splat.Ninject/README.md
  src/Splat.Ninject/Splat.Ninject.csproj
  src/Splat.Ninject/SplatNinjectExtensions.cs
  src/Splat.sln
Labels: Feature
